name: Upload Python Package to PyPI

on:
  push:
    tags:
    - '*'
  release:
    types: [created, published]

permissions:
  contents: read

jobs:
  publish:
    name: build package
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install Pillow numpy filetype setuptools wheel twine
    - name: Build Source and Wheel Distributions
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish Distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_PYPALEX_API_TOKEN }}
